export default [
  {
    id: 'nature',
    heading: 'nature',
    type: 'radio',
    options: ['introvert', 'extrovert', 'ambivert'],
  },
  {
    id: 'dietaryPreferences',
    heading: 'Dietary Preferences',
    type: 'radio',
    options: ['Vegetarian', 'Non-Vegetarian'],
  },
  {
    id: 'workStyle',
    heading: 'Work Style',
    type: 'radio',
    options: ['Works from Home', 'Goes To Office', 'Hybrid Work Setting'],
  },
  {
    id: 'workHours',
    heading: 'Work Hours',
    type: 'radio',
    options: ['Daytime Shift', 'Nighttime Shift'],
  },
  {
    id: 'smokingPreference',
    heading: 'Smoking Preference',
    type: 'radio',
    options: ['Smoker', 'Non-Smoker'],
  },
  {
    id: 'drinkingPreference',
    heading: 'Drinking Preference',
    type: 'radio',
    options: ['Social Drinker', 'Frequent Drinker', 'Teetotaller'],
  },
  {
    id: 'guestPolicy',
    heading: 'Guest Policy',
    type: 'radio',
    options: [
      'Have Guests Over Often',
      'Have Guests Over Occasionally',
      'Have Guests Over Rarely',
    ],
  },
  {
    id: 'regionalBackground',
    heading: 'Regional Background',
    type: 'radio',
    options: [
      'North India',
      'East India',
      'West India',
      'South India',
      'North-East India',
      'Central India',
    ],
  },
  {
    id: 'interests',
    heading: 'Hobbies & Interests',
    type: 'checkbox',
    options: [
      'Books',
      'Movies',
      'Gym',
      'Traveling',
      'Sports',
      'Dance',
      'Partying',
      'Gaming',
      'Music',
      'Cooking',
      'Anime',
    ],
  },
]
